# Generated by Django 4.2.30 on 2026-05-14 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decoration',
            name='event',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='event',
        ),
        migrations.RemoveField(
            model_name='functionhall',
            name='event',
        ),
        migrations.RemoveField(
            model_name='serviceitem',
            name='event',
        ),
    ]
